Change fonts to Palatino, Helvetica, and 1.5 line
MiniFate/MiniFate pull request #38
Opened 2021-01-04 05:58 UTC by agude

Going from this: 

<img width="822" alt="Screen Shot 2021-01-03 at 9 58 02 PM" src="https://user-images.githubusercontent.com/4562016/103505303-c5349b80-4e0e-11eb-85e8-45b2f8a421de.png">

To this:

<img width="798" alt="Screen Shot 2021-01-03 at 9 58 21 PM" src="https://user-images.githubusercontent.com/4562016/103505327-d2518a80-4e0e-11eb-8130-557c238044f1.png">

2021-01-04 20:53 UTC, charles-uno requested changes

2021-01-04 20:53 UTC, charles-uno commented on _chapters/01-introduction.md
> +## Introduction
Why are we skipping h1?

2021-01-04 20:53 UTC, charles-uno commented on assets/_sass/main.scss
> +main {
👀

2021-01-04 20:53 UTC, charles-uno commented on index.md
> +# {{ site.title }}
I prefer having title be a class, rather than hijacking h1. Easier to read the Markdown, easier to read the CSS, and eventually the title will probably be in the navbar rather than the main block anyway

2021-01-04 21:11 UTC, agude commented
Taking conversation to this level since it covers multiple things up-top:

1. All headings have been demoted one level because we should have **EXACTLY** one <h1> tag on each page. With our current concat strategy we had one per chapter.
2. I don't know what you mean by "a class" for `{{ site.title }}`. Currently I'm only using that to set the <h1> on the main page to "MiniFate". We could just hard-code it too. I think `site.title` is ... maybe not a useful variable ever for us?

Another thing I noticed: we are going to want to make a new layout probably for the "GIANT CONCATING PAGE", since it's unlikely any other page will do exactly what it does...

2021-01-04 21:13 UTC, charles-uno commented
What I mean is, I prefer
<div class="title">{{site.title}}</div>
# Introduction

over

# {{site.title}}
## Introduction

since title is (at least in mind) a qualitatively different thing, and will
likely be positioned and formatted differently from a header

On Mon, Jan 4, 2021 at 3:11 PM Alexander Gude <notifications@github.com>
wrote:

> Taking conversation to this level since it covers multiple things up-top:
>
>    1. All headings have been demoted one level because we should have
>    *EXACTLY* one <h1> tag on each page. With our current concat strategy
>    we had one per chapter.
>    2. I don't know what you mean by "a class" for {{ site.title }}.
>    Currently I'm only using that to set the <h1> on the main page to
>    "MiniFate". We could just hard-code it too. I think site.title is ...
>    maybe not a useful variable ever for us?
>
> Another thing I noticed: we are going to want to make a new layout
> probably for the "GIANT CONCATING PAGE", since it's unlikely any other page
> will do exactly what it does...
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/MiniFate/MiniFate/pull/38#issuecomment-754221335>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABO7IW3Y6JHARUZW7OOB7ZTSYIVIHANCNFSM4VSRGXUA>
> .
>

2021-01-04 21:16 UTC, agude commented
Ok, agree!

But we still need to fix the `<h1>` issue; are the chapters going to live separately? If not, then I think demoting them all to `<h2>` is the right move.

2021-01-05 01:45 UTC, charles-uno approved these changes

2021-01-05 01:45 UTC, charles-uno commented on index.md
> +<h1 class="page-title">{{ page.title }}</h1>
Should index.md also eat 00-header.md?

2021-01-05 02:58 UTC, merged