Draft of challenges
MiniFate/MiniFate pull request #80
Opened 2021-06-18 16:44 UTC by agude

I hear you like examples so I wrote a huge huge huge example. :-/

2022-10-25 17:11 UTC, charles-uno commented on _chapters/06-combat-and-conflicts.md
> +solve the problem. The GM will set out a list of tasks that must be
I don't love "solve the problem". Doesn't really line up with the primary use case of crushing zombies. Maybe "overcome the obstacle"? Still not great

2022-10-25 17:12 UTC, charles-uno commented on _chapters/06-combat-and-conflicts.md
> +> - Avoid the mega cacti that are just now peaking out of the clouds
peeking

2022-10-25 17:13 UTC, charles-uno commented on _chapters/06-combat-and-conflicts.md
> +### Challenges
Not sure I get it. This seems like normal play? But the GM is laying tracks for you

2022-10-25 17:15 UTC, charles-uno commented on _chapters/06-combat-and-conflicts.md
> +> but I'm also a trained mage. I have studied lots of arcane books before in
double "before". 

did we eventually prefer line breaks at sentence breaks rather than at a set column?

2022-10-25 17:18 UTC, charles-uno requested changes
Seems like there should be two modes of play:
- Collaborative narration: unstructured order, lots of talking, occasional rolls
- Combat: go around the table, pretty much everyone rolls each turn

This feels like something in between. I guess I don't get it

2022-10-26 15:12 UTC, agude commented
Is it worth iterating on these now? They're like a year out of date. 😄 Presumably we'll steal some parts.

2022-11-01 16:10 UTC, merged